# Generated by Django 4.2.4 on 2023-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("particleWebsiteApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="particle",
            name="charge",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
