# Generated by Django 4.2.4 on 2023-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("particleWebsiteApp", "0002_alter_particle_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="particle",
            name="charge",
            field=models.CharField(max_length=10),
        ),
    ]
